name: CI/CD Workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore src/WeatherForecastApi.ApiService
   
    - name: Build
      run: dotnet build --no-restore src/WeatherForecastApi.ApiService
    
    - name: Test
      run: dotnet test src/tests/WeatherForecastApi.IntegrationTests
    
    - name: Publish
      run: dotnet publish src/WeatherForecastApi.Web -c Release --output ./publish


    - name: ZIP publish
      run: zip -r src/publish.zip .
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Upload to S3
      run: | 
        aws s3 cp ./publish s3://appdeploygit/githubactions/ --recursive

    - name: Deploy to EC2 instance
      run: |
        aws deploy create-deployment --application-name myapp --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name myappdeploy --s3-location bucket=appdeploygit,key=githubactions/publish.zip,bundleType=zip
